### ISSUE TITLE
Processors in pipelines not working in versions 7.0.23, 7.0.24 and 7.0.25 using  get_stroom.sh 

### ISSUE THREAD

**Issue by ghost** [gchq/stroom-resources#117]
Since version 7.0.23 using get_stroom.sh, the processors in the pipelines are not working any more.
Using the big blue stepping button at the bottom right of the bottom data pane it process the data.

I tried versions:
- [stroom-stacks-v7.0.23](https://github.com/gchq/stroom-resources/releases/tag/stroom-stacks-v7.0.23)
- [stroom-stacks-v7.0.24](https://github.com/gchq/stroom-resources/releases/tag/stroom-stacks-v7.0.24)
- [stroom-stacks-v7.0.25](https://github.com/gchq/stroom-resources/releases/tag/stroom-stacks-v7.0.25)

Rolling back to 7.0.22 it works fine again.

Maybe there is an option to configure, I'm a new comer in the community.

**Comment by stroomdev10** [comment]
v7.0.23 created a new managed job called `Processor Task Creator` , this needs to be enabled to create processing tasks

![image](https://github.com/gchq/stroom-resources/assets/28703366/40b370f0-1334-4923-86b4-bb8d46d65f05)
